module.exports = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Platform',
      collapsible: false,
      items: [{
        'Firefox Accounts': ['platform/firefox-accounts/fxa-overview',
                             'platform/firefox-accounts/integration-with-fxa',
                             'platform/firefox-accounts/pairing'],
        'Firefox Push': ['platform/firefox-push/push-feature',
                         'platform/firefox-push/push-design',
                         'platform/firefox-push/push-development',
                         'platform/firefox-push/push-history'],
        'Firefox Sync': ['platform/firefox-sync/storage-feature',
                         'platform/firefox-sync/account-management-feature',
                         'platform/firefox-sync/sync-testing',
                         'platform/firefox-sync/using-the-staging-environment'],
        'Subscription Platform': ['platform/sub-plat/sub-plat-overview',
                                  'platform/sub-plat/sub-plat-features',
                                  'platform/sub-plat/integration-with-subscription-platform',
                                  'platform/sub-plat/coupons'],
      }]
    },
    {
      type: 'category',
      label: 'For FxA Engineers',
      items: [
        'fxa-engineering/fxa-dev-process',
        'fxa-engineering/fxa-work-breakdown-process',
        'fxa-engineering/release-process',
        'fxa-engineering/fxa-incident-response',
        'fxa-engineering/fxa-api',
        'fxa-engineering/fxa-system-diagrams',
        'fxa-engineering/fxa-logging',
        'fxa-engineering/automation-test-plan',
        'fxa-engineering/vscode-development',
        'fxa-engineering/fxa-sub-platform',
        {
          'Topic Deep Dives': ['fxa-engineering/fxa-email',
                               'fxa-engineering/fxa-metrics',
                               'fxa-engineering/fxa-localization',
                               'fxa-engineering/fxa-jwt-access-tokens',
                               'fxa-engineering/fxa-scoped-keys',
                               'fxa-engineering/fxa-onepw-protocol',
                               'fxa-engineering/fxa-webchannel-protocol',
                               'fxa-engineering/fxa-oauth-webchannel-protocol',
                               'fxa-engineering/fxa-content-server-ab-testing',
                               'fxa-engineering/fxa-tests-circleci',
                               'fxa-engineering/functional-testing',
                               'fxa-engineering/fxa-content-server-architecture',
                               'fxa-engineering/fxa-session-tokens',
                               'fxa-engineering/interruptive-surveys',
                               'fxa-engineering/fxa-github',
          ],
        },
        'fxa-engineering/fxa-adr',
        'fxa-engineering/fxa-scheduled-maintenance',
        'fxa-engineering/fxa-additional-docs',
    ]
    },    
  ],
};
